#!/bin/bash

mapfile -t units
for unit in "${units[@]}"
do
    type=${unit#usr/lib/systemd/}
    type=${type%/*.*}
    unit=${unit#usr/lib/systemd/*/}
    if [[ $unit == *@.* ]]; then
        unit=${unit/@/@*}
        mapfile -t units < <(/usr/bin/find /etc/systemd/"$type"/*.wants -name "$unit")
        unit=${units[*]#/etc/systemd/$type/*.wants/}
        if [[ ! $unit ]]; then
            continue
        fi
    fi
    case $type in
        system)
            /usr/bin/systemctl disable --now $unit
            ;;
        user)
            /usr/bin/systemctl --global disable --now $unit
            ;;
    esac
done

# vim: set ft=sh ts=4 sw=4 et:
