#!/bin/bash

mapfile -t unitpaths
for unitpath in "${unitpaths[@]}"
do
    if [[ -L $unitpath || ! -f $unitpath ]]; then
        continue
    fi
    type=${unitpath#usr/lib/systemd/}
    type=${type%/*.*}
    unit=${unitpath#usr/lib/systemd/$type/}
    case $type in
        system)
            /usr/bin/systemctl disable --no-reload "$unit"
            /usr/bin/systemctl stop "${unit/@/@*}"
            ;;
        user)
            /usr/bin/systemctl --global disable "$unit"
            ;;
    esac
done

# vim: set ft=sh ts=4 sw=4 et:
