#!/bin/bash
user_stops=()

mapfile -t unitpaths
for unitpath in "${unitpaths[@]}"
do
    IFS='/' read -ra unitarray <<< "$unitpath"
    # if the path leads to a drop-in file, a dir or a symlink, we skip it
    if (( ${#unitarray[@]} > 5 )) || [[ ! -f $unitpath || -L $unitpath ]]; then
        continue
    fi

    type=${unitarray[3]}
    unit=${unitarray[4]}
    case $type in
        system)
            /usr/bin/systemctl disable --no-reload "$unit"
            /usr/bin/systemctl stop "${unit/@/@*}"
            ;;
        user)
            /usr/bin/systemctl --global disable "$unit"
            user_stops+=("${unit/@/@*}")
            ;;
    esac
done

if (( ${#user_stops[@]} )); then
    printf "==> Use \`systemctl --user stop %s' to stop all remaining units in user manager\n" "${user_stops[*]}"
fi

# vim: set ft=sh ts=4 sw=4 et:
